[project]
name = "facebook-claim-annotation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "blinker>=1.9.0",
    "pandas>=1.5.0",
    "pillow>=9.0.0",
    "pymongo>=4.5.0",
    "streamlit>=1.28.0",
]
